# Generated by Django 2.2.7 on 2019-11-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文件ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('file_path', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '文件路径',
                'db_table': 'tb_filepath',
            },
        ),
    ]
