# Generated by Django 2.2.7 on 2019-11-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0002_filepath_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformTask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='任务id')),
                ('name', models.CharField(max_length=50)),
                ('parameter', models.CharField(max_length=100, null=True, verbose_name='任务参数')),
                ('command', models.CharField(max_length=50, null=True, verbose_name='执行程序命令')),
                ('excute_path', models.CharField(max_length=100, null=True, verbose_name='可执行文件路径')),
                ('save_path', models.CharField(max_length=100, null=True, verbose_name='文件存储位置')),
            ],
            options={
                'verbose_name': '任务',
                'db_table': 'tb_task',
            },
        ),
    ]
