# Generated by Django 2.2.7 on 2019-11-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0003_transformtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformtask',
            old_name='parameter',
            new_name='default_parameter',
        ),
    ]
