# Generated by Django 2.2.7 on 2019-11-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0004_auto_20191120_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepath',
            name='transform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_task', to='transform.TransformTask'),
            preserve_default=False,
        ),
    ]
