# Generated by Django 2.2.7 on 2019-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0005_filepath_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformtask',
            name='upload_file',
            field=models.BooleanField(default=False, verbose_name='是否需要上传文档'),
        ),
        migrations.AlterField(
            model_name='transformtask',
            name='excute_path',
            field=models.CharField(max_length=100, null=True, verbose_name='可执行程序路径'),
        ),
    ]
